---
# handlers file for systemd_networkd
- name: "Restart Systemd-Networkd."
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - systemd-networkd
  become: yes
  listen:
    - "restart systemd-networkd"
  when:
    - inventory_hostname in groups['sssd'] | default([])
    - autonomy_sssd_package in ansible_facts.packages
